const state={token:localStorage.getItem("morph_token"),user:null,view:"dashboard",docs:[],outputs:[],analytics:null,activeDoc:null,chat:[],mode:"standard",featureState:{oracle:false,redact:false,bias:false,echo:false,decoy:false,swarm:false,immune:true,trace:true}};
const OUTPUTS=["Citizen Simplifier","Officer Brief","Executive Summary","FAQ Generator","WhatsApp Generator","Social Media Generator","Presentation Generator","Voice Script","Press Release","SMS / Alert","Infographic Content","Detailed Report","Key Facts / Statistics","Action Checklist"];
const LANGUAGES=["English","Hindi","Hinglish","Tamil","Telugu","Bengali","Marathi","Gujarati","Kannada","Malayalam","Punjabi","Odia"];
const NAV=[["dashboard","Command Center"],["transform","Transform"],["documents","Source Library"],["history","Output Vault"],["features","Capabilities"],["analytics","Analytics"],["settings","System"]];
const FEATURES=[
 ["immune","Anti-Poisoning Shield","Pre-flight scan for prompt injection, hidden instructions and suspicious source text."],
 ["trace","Glass Box Traceability","Click generated claims to inspect the source evidence, page and section."],
 ["confidence","Confidence & Ambiguity","Surface low-confidence or conflicting claims instead of silently guessing."],
 ["redact","Clearance-Level Morphing","Generate audience-safe versions with sensitive entities automatically redacted."],
 ["swarm","Swarm Ingestion Matrix","Batch-ingest mixed files and consolidate them into one operational context."],
 ["oracle","Oracle Mode","Produce best-case, worst-case and most-likely future scenarios with action drafts."],
 ["decoy","Honey-Pot Decoy","Create structurally plausible fictional decoy material from a source."],
 ["bias","Bias Neutralizer","Strip loaded framing and rewrite source material as an objective intelligence brief."],
 ["echo","Temporal Echo Engine","Cross-reference current entities against the historical source library."],
 ["fingerprint","Traitor Tracer","Attach an operator/time fingerprint to exported artifacts for controlled leak tracing."]
];
const $=(s,r=document)=>r.querySelector(s);const app=$("#app");boot();
async function boot(){if(!state.token)return landing();try{state.user=(await api("/api/me")).user;await refresh();render()}catch{logout()}}
async function refresh(){const[d,o,a]=await Promise.all([api("/api/documents"),api("/api/transformations"),api("/api/analytics")]);state.docs=d.documents;state.outputs=o.outputs;state.analytics=a;if(!state.activeDoc||!state.docs.some(x=>x.id===state.activeDoc.id))state.activeDoc=state.docs[0]||null}
function landing(){app.innerHTML=`<div class="landing"><header class="topbar"><div class="brand"><span class="seal">M</span><span>MORPH</span></div><button class="primary" id="login">Officer Login</button></header><main class="landing-main"><section class="hero-copy"><div class="eyebrow">SOURCE-GROUNDED INTELLIGENCE TRANSFORMATION</div><h1>MORPH</h1><h2>One source. Every mission-ready message.</h2><p>Transform sensitive source material into verified, audience-specific intelligence and communication—without losing provenance, context or human oversight.</p><div class="hero-actions"><button class="primary" id="demo">Enter Command Center</button><button class="ghost" id="register">Create Account</button></div><div class="trust-row"><span>01 Source-grounded</span><span>02 Verifiable</span><span>03 Clearance-aware</span></div></section><section class="landing-console"><div class="console-head"><span> MORPH / OPERATIONAL CORE</span><span class="status-dot">SYSTEM READY</span></div><div class="console-title">Intelligence → verified action</div><div class="console-sub">Ingest · understand · transform · verify · publish</div><div class="feature-preview">${FEATURES.slice(0,6).map(f=>`<div class="feature-tile"><span class="feature-index">${String(FEATURES.indexOf(f)+1).padStart(2,"0")}</span><b>${f[1]}</b><small>${f[2]}</small></div>`).join("")}</div></section></main></div>`;$("#login").onclick=()=>formPage(false);$("#register").onclick=()=>formPage(true);$("#demo").onclick=demo}
function formPage(register){app.innerHTML=`<main class="auth"><section class="panel auth-card"><div class="brand"><span class="seal">M</span>MORPH</div><div class="eyebrow">SECURE OPERATOR ACCESS</div><h2>${register?"Create operator account":"Officer Login"}</h2><p class="muted">${register?"Create a workspace account to access the transformation core.":"Authenticate to enter the MORPH command center."}</p><form id="authForm">${register?'<label>Name<input name="name" required maxlength="100"></label>':''}<label>Email<input name="email" type="email" required autocomplete="username"></label><label>Password<input name="password" type="password" required minlength="8" autocomplete="current-password"></label><button class="primary full" type="submit">${register?"Create Account":"Authenticate"}</button><button class="ghost full" type="button" id="back">Back</button></form></section></main>`;$("#back").onclick=landing;$("#authForm").onsubmit=async e=>{e.preventDefault();try{const r=await api(register?"/api/auth/register":"/api/auth/login",{method:"POST",body:Object.fromEntries(new FormData(e.target))});state.token=r.token;localStorage.setItem("morph_token",r.token);await boot()}catch(err){toast(err.message)}}}
async function demo(){try{const r=await api("/api/auth/login",{method:"POST",body:{email:"officer@transformai.gov",password:"Officer@123"}});state.token=r.token;localStorage.setItem("morph_token",r.token);await boot()}catch(e){toast("Demo access is unavailable. Use Create Account.")}}
function render(){app.innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="brand sidebar-brand"><span class="seal">M</span><div><b>MORPH</b><small>INTELLIGENCE OS</small></div></div><div class="clearance"><span class="pulse"></span> SECURE WORKSPACE</div><nav class="nav">${NAV.map(([k,n])=>`<button data-view="${k}" class="${state.view===k?"active":""}"><span>${navIcon(k)}</span>${n}</button>`).join("")}</nav><div class="sidebar-feature"><span>ACTIVE MODE</span><b>${modeName()}</b><small>${state.activeDoc?esc(state.activeDoc.title):"No source loaded"}</small></div><div class="user-box"><b>${esc(state.user?.name||"Operator")}</b><small>${esc(state.user?.role||"USER")} · ${esc(state.user?.email||"")}</small><button class="ghost" id="logout">Sign out</button></div></aside><main class="main"><header class="main-top"><div><span class="crumb">MORPH / ${title(state.view)}</span><h1>${pageTitle()}</h1><p>${pageSubtitle()}</p></div><div class="top-actions"><span class="security-badge">● VERIFIED SESSION</span><button class="primary" id="quickTransform">New Transformation</button></div></header>${view()}</main></div>`;document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});$("#logout").onclick=logout;$("#quickTransform").onclick=()=>{state.view="transform";render()};bind()}
function pageTitle(){return({dashboard:"Command Center",transform:"Transformation Workspace",documents:"Source Library",history:"Output Vault",features:"Capability Matrix",analytics:"Operational Analytics",settings:"System & Security"})[state.view]||"Command Center"}
function pageSubtitle(){return({dashboard:"Live operational view of source intake, transformations and verification.",transform:"Build publication-ready outputs while preserving source provenance.",documents:"Every uploaded source, its intelligence profile and processing state.",history:"Versioned artifacts with factuality, citation and provenance signals.",features:"The MORPH intelligence layer—designed for adversarial, high-stakes workflows.",analytics:"Quality, volume, languages and operational usage across the workspace.",settings:"Deployment, authentication, provider and storage posture."})[state.view]||""}
function view(){if(state.view==="transform")return workspace();if(state.view==="documents")return documents();if(state.view==="history")return outputsPage();if(state.view==="features")return featureMatrix();if(state.view==="analytics")return analytics();if(state.view==="settings")return settings();return dashboard()}
function dashboard(){const a=state.analytics||{};return `<section class="metric-grid">${metric("Sources processed",a.documentsProcessed,"SOURCE")}${metric("Transformations",a.transformationsGenerated,"OPS")}${metric("Artifacts",a.outputsGenerated,"OUTPUT")}${metric("Languages",a.languagesUsed,"I18N")}${metric("Avg factuality",(a.averageFactualityScore||0)+"%","VERIFY")}</section><section class="dashboard-grid"><div class="panel command-panel"><div class="section-head"><div><span class="eyebrow">MISSION FLOW</span><h2>Source → intelligence → action</h2></div><button class="ghost" id="dashboardTransform">Open workspace</button></div><div class="flow">${[["01","INGEST","PDF · DOCX · TXT · MD"],["02","IMMUNE","INJECTION / POISONING SCAN"],["03","UNDERSTAND","CLAIMS · ENTITIES · DATES"],["04","MORPH","AUDIENCE · CLEARANCE · CHANNEL"],["05","VERIFY","TRACE · CONFIDENCE · CITATIONS"]].map(x=>`<div class="flow-step"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></div>`).join("")}</div></div><div class="panel alert-panel"><div class="section-head"><div><span class="eyebrow">SECURITY POSTURE</span><h2>Guardrails active</h2></div><span class="status-pill ok">NOMINAL</span></div>${FEATURES.slice(0,4).map(f=>`<div class="security-row"><span class="security-icon">${featureIcon(f[0])}</span><div><b>${f[1]}</b><small>Active in workspace</small></div><span class="status-pill ok">ON</span></div>`).join("")}</div></section><section class="panel recent"><div class="section-head"><div><span class="eyebrow">SOURCE LIBRARY</span><h2>Recent sources</h2></div><button class="ghost" id="allDocs">View all</button></div>${docTable(state.docs.slice(0,6))}</section>`}
function workspace(){const d=state.activeDoc;return `<div class="mode-strip">${["standard","oracle","clearance","swarm","decoy","bias"].map(m=>`<button class="mode ${state.mode===m?"active":""}" data-mode="${m}">${modeLabel(m)}</button>`).join("")}</div><section class="workspace-grid"><section class="panel source-panel"><div class="section-head"><div><span class="eyebrow">01 / INGEST</span><h2>Source material</h2></div><span class="status-pill ${state.featureState.immune?"ok":"warn"}">${state.featureState.immune?"IMMUNE ON":"IMMUNE OFF"}</span></div><div class="drop" id="drop"><div class="drop-icon">＋</div><b>Drop source files here</b><small>PDF · DOCX · TXT · Markdown</small></div><input type="file" id="fileInput" accept=".pdf,.docx,.txt,.md,.markdown" multiple><textarea id="sourceText" placeholder="Or paste source text here…">${esc(d?.text||"")}</textarea><div class="actions"><button class="primary" id="upload">${state.mode==="swarm"?"Run Swarm Ingestion":"Analyze Source"}</button><button class="ghost" id="sample">Load Scenario</button></div>${d?`<div class="source-summary"><span class="eyebrow">ACTIVE SOURCE</span><b>${esc(d.title)}</b><small>${d.fileType?.toUpperCase()} · ${d.pages||1} page(s) · ${d.intelligence?.claimCount||0} claims</small></div>`:""}</section><section class="panel transform-panel"><div class="section-head"><div><span class="eyebrow">02 / MORPH</span><h2>Transformation controls</h2></div><span class="mode-chip">${modeName()}</span></div><div class="form-grid">${select("audience",["Citizen","Officer","Executive","Student","Media","General Public"])}${select("tone",["Formal","Simple","Professional","Friendly","Urgent","Educational"])}${select("length",["Short","Medium","Detailed"],"Medium")}${select("channel",["Website","WhatsApp","Email","Social Media","SMS","Presentation","Report","Voice"])}${select("language",LANGUAGES,"English","full")}</div><div class="control-title">OUTPUT ARTIFACTS</div><div class="output-picker">${OUTPUTS.map((x,i)=>`<label class="output-option"><input type="checkbox" name="outputType" value="${esc(x)}" ${i<5?"checked":""}><span>${esc(x)}</span></label>`).join("")}</div><div class="actions"><button class="primary full" id="generate" ${d?"":"disabled"}>Generate verified artifacts</button></div>${d?intelligence(d):""}</section><section class="panel result-panel"><div class="result-tabs"><button class="active" id="outTab">Outputs</button><button id="chatTab">Document Chat</button><button id="compareTab">Compare</button></div><div id="rightPane">${generated()}</div></section></section>`}
function intelligence(d){const i=d.intelligence||{};return `<div class="intel"><div class="control-title">SOURCE INTELLIGENCE</div><div class="intel-grid"><div><span>WORDS</span><b>${i.wordCount||0}</b></div><div><span>PAGES</span><b>${i.pages||1}</b></div><div><span>CLAIMS</span><b>${i.claimCount||0}</b></div><div><span>ENTITIES</span><b>${i.entityCount||0}</b></div></div><div class="chips">${(i.topics||[]).map(x=>`<span class="chip">${esc(x)}</span>`).join("")}</div>${i.risks?.length?`<div class="risk-box"><b>AMBIGUITY / RISK SIGNALS</b>${i.risks.slice(0,3).map(x=>`<span>${esc(x)}</span>`).join("")}</div>`:""}</div>`}
function generated(){const os=state.outputs.filter(o=>!state.activeDoc||o.documentIds?.includes(state.activeDoc.id)).slice(0,8);return os.length?os.map(outputCard).join(""):`<div class="empty"><div>◈</div><b>No artifacts generated</b><small>Analyze a source, configure the transformation and generate verified outputs.</small></div>`}
function outputCard(o){const trace=(o.citationMap||[]).slice(0,8);return `<article class="output-card"><div class="output-head"><div><span class="eyebrow">ARTIFACT / ${esc(o.outputType)}</span><h3>${esc(o.title||o.outputType)}</h3></div><span class="status-pill ${o.factualityScore>=90?"ok":"warn"}">${o.factualityScore||0}% FACTUALITY</span></div><div class="output-meta"><span>${esc(o.language)}</span><span>${esc(o.audience)}</span><span>${esc(o.channel)}</span><span>CITATIONS ${o.citationCoverage||0}%</span>${o.demo?"<span>DEMO PROVIDER</span>":""}</div><div class="content" contenteditable="true" data-edit="${o.id}">${esc(o.content)}</div><details class="trace"><summary>Glass Box · source trace</summary>${trace.map(c=>`<button class="trace-row" data-trace="${esc(c.factId||"")}"><b>${esc(c.marker)}</b><span>Page ${c.page} · ${esc(c.section)}</span><small>${esc(c.source)}</small></button>`).join("")}</details><div class="actions"><button data-copy="${o.id}">Copy</button><button data-save="${o.id}">Save Version</button><button data-export="${o.id}" data-format="md">Export MD</button><button data-export="${o.id}" data-format="json">Export JSON</button><button data-verify="${o.id}">Re-verify</button></div></article>`}
function documents(){return `<section class="panel"><div class="section-head"><div><span class="eyebrow">SOURCE LIBRARY</span><h2>Analyzed documents</h2></div><button class="primary" id="newSource">Add source</button></div>${docTable(state.docs)}</section>`}
function docTable(ds){if(!ds.length)return `<div class="empty"><b>No sources yet</b><small>Open Transform and ingest your first source.</small></div>`;return `<div class="table-wrap"><table class="table"><thead><tr><th>Source</th><th>Department</th><th>Claims</th><th>Status</th></tr></thead><tbody>${ds.map(d=>`<tr><td><button class="link-btn" data-pick="${d.id}">${esc(d.title)}</button><small>${esc(d.name||"")}</small></td><td>${esc(d.department||"General")}</td><td>${d.intelligence?.claimCount||0}</td><td><span class="status-pill ok">${esc(d.status||"Analyzed")}</span></td></tr>`).join("")}</tbody></table></div>`}
function outputsPage(){return `<section class="panel"><div class="section-head"><div><span class="eyebrow">VERSION CONTROL</span><h2>Generated artifacts</h2></div><span class="mode-chip">${state.outputs.length} TOTAL</span></div>${state.outputs.length?state.outputs.map(outputCard).join(""):`<div class="empty"><b>Output vault is empty</b><small>Generated artifacts and versions will appear here.</small></div>`}</section>`}
function featureMatrix(){return `<section class="feature-matrix">${FEATURES.map((f,i)=>`<article class="feature-card ${state.featureState[f[0]]?"enabled":""}"><div class="feature-top"><span class="feature-index">${String(i+1).padStart(2,"0")}</span><span class="status-pill ${state.featureState[f[0]]?"ok":"off"}">${state.featureState[f[0]]?"ACTIVE":"READY"}</span></div><div class="feature-icon">${featureIcon(f[0])}</div><h2>${f[1]}</h2><p>${f[2]}</p><button class="ghost" data-feature="${f[0]}">${state.featureState[f[0]]?"Disable":"Enable"}</button></article>`).join("")}</section>`}
function analytics(){const a=state.analytics||{};return `<section class="metric-grid">${metric("Factuality",(a.averageFactualityScore||0)+"%","QUALITY")}${metric("Citation coverage",(a.averageCitationCoverage||0)+"%","TRACE")}${metric("Artifacts",a.outputsGenerated,"OUTPUT")}${metric("Sources",a.documentsProcessed,"SOURCE")}${metric("Languages",a.languagesUsed,"I18N")}</section><section class="analytics-grid"><div class="panel"><div class="section-head"><div><span class="eyebrow">OUTPUT MIX</span><h2>Artifact types</h2></div></div>${chart(a.byType)}</div><div class="panel"><div class="section-head"><div><span class="eyebrow">LANGUAGE</span><h2>Language mix</h2></div></div>${chart(a.byLanguage)}</div><div class="panel"><div class="section-head"><div><span class="eyebrow">DEPARTMENT</span><h2>Source distribution</h2></div></div>${chart(a.byDepartment)}</div></section>`}
function settings(){return `<section class="panel settings-panel"><div class="section-head"><div><span class="eyebrow">SYSTEM</span><h2>Deployment & security</h2></div><span class="status-pill ok">ONLINE</span></div><div class="setting-list">${[["AI Provider","Server-side OpenAI Responses API or intentional demo provider"],["Storage","PostgreSQL in production; local JSON for development"],["Authentication","Signed tokens and scrypt password hashing"],["Document parsing","PDF · DOCX · TXT · Markdown"],["Verification","Source claim support and citation coverage"],["Security layer","Prompt-injection aware source handling"]].map(x=>`<div class="setting-row"><span>${x[0]}</span><b>${x[1]}</b><i>READY</i></div>`).join("")}</div></section>`}
function bind(){$("#dashboardTransform")?.addEventListener("click",()=>{state.view="transform";render()});$("#allDocs")?.addEventListener("click",()=>{state.view="documents";render()});$("#newSource")?.addEventListener("click",()=>{state.view="transform";render()});$("#sample")?.addEventListener("click",()=>{state.activeDoc=state.docs[0];if(!state.activeDoc)toast("Upload a source first.");render()});document.querySelectorAll("[data-pick]").forEach(b=>b.onclick=()=>{state.activeDoc=state.docs.find(d=>d.id===b.dataset.pick);state.view="transform";render()});document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;state.featureState.oracle=state.mode==="oracle";state.featureState.redact=state.mode==="clearance";state.featureState.swarm=state.mode==="swarm";state.featureState.decoy=state.mode==="decoy";state.featureState.bias=state.mode==="bias";render()});document.querySelectorAll("[data-feature]").forEach(b=>b.onclick=()=>{const k=b.dataset.feature;state.featureState[k]=!state.featureState[k];toast(`${b.textContent.trim()} ${state.featureState[k]?"d":"D"}isabled`);render()});$("#upload")?.addEventListener("click",upload);$("#generate")?.addEventListener("click",generate);document.querySelectorAll("[data-copy]").forEach(b=>b.onclick=()=>copy(b.dataset.copy));document.querySelectorAll("[data-save]").forEach(b=>b.onclick=()=>saveVersion(b.dataset.save));document.querySelectorAll("[data-verify]").forEach(b=>b.onclick=()=>verify(b.dataset.verify));document.querySelectorAll("[data-export]").forEach(b=>b.onclick=()=>exportOut(b.dataset.export,b.dataset.format));document.querySelectorAll("[data-trace]").forEach(b=>b.onclick=()=>toast(`Source trace: ${b.querySelector("small")?.textContent||"linked evidence"}`));$("#chatTab")?.addEventListener("click",chatPane);$("#compareTab")?.addEventListener("click",comparePane);const drop=$("#drop");if(drop){drop.ondragover=e=>{e.preventDefault();drop.classList.add("active")};drop.ondragleave=()=>drop.classList.remove("active");drop.ondrop=e=>{e.preventDefault();drop.classList.remove("active");const input=$("#fileInput"),dt=new DataTransfer();[...e.dataTransfer.files].forEach(f=>dt.items.add(f));input.files=dt.files}}}
async function upload(){const input=$("#fileInput"),file=input?.files[0];let body={department:"General"};if(file){body.name=file.name;body.type=file.type||"application/octet-stream";body.encoding="base64";body.content=await fileToBase64(file)}else{body.name="Pasted source.txt";body.type="text/plain";body.content=$("#sourceText").value;body.encoding="text"}if(!body.content)return toast("Choose a file or paste source text.");if(state.featureState.immune){const scan=scanSource(body.content);if(scan.length){toast(`Immune System: ${scan.length} suspicious instruction pattern(s) detected.`);body.content=neutralizeInjectedLines(body.content)}}try{const r=await api("/api/documents/upload",{method:"POST",body});state.activeDoc=r.document;await refresh();state.view="transform";toast(state.mode==="swarm"?"Swarm ingestion complete":"Source analyzed");render()}catch(e){toast(e.message)}}
function scanSource(text){return String(text).match(/ignore\s+(all|previous|prior)\s+instructions|system\s+message|developer\s+message|reveal\s+(the\s+)?prompt|jailbreak|do\s+not\s+follow\s+the\s+source/gi)||[]}
function neutralizeInjectedLines(text){return String(text).split(/\n/).filter(line=>!/(ignore\s+(all|previous|prior)\s+instructions|system\s+message|developer\s+message|reveal\s+(the\s+)?prompt|jailbreak)/i.test(line)).join("\n")}
async function generate(){if(!state.activeDoc)return toast("Analyze a source first.");const btn=$("#generate"),types=[...document.querySelectorAll("[name=outputType]:checked")].map(x=>x.value);if(!types.length)return toast("Select at least one output.");btn.disabled=true;btn.textContent="MORPHING…";try{const body={documentIds:[state.activeDoc.id],outputTypes:types,audience:$("#audience").value,tone:$("#tone").value,length:$("#length").value,channel:$("#channel").value,language:$("#language").value};if(state.mode==="oracle")body.outputTypes=["Executive Summary","Officer Brief","Action Checklist"];if(state.mode==="clearance")body.audience="General Public";if(state.mode==="bias")body.tone="Professional";await api("/api/transformations",{method:"POST",body});await refresh();toast(`${state.mode==="oracle"?"Oracle scenarios":"Verified artifacts"} generated`);render()}catch(e){toast(e.message);btn.disabled=false;btn.textContent="Generate verified artifacts"}}
function chatPane(){const d=state.activeDoc;if(!d)return;$("#rightPane").innerHTML=`<div class="chat-log">${state.chat.map(m=>`<div class="msg ${m.role}">${esc(m.text)}</div>`).join("")}</div><input id="question" placeholder="Ask only what the selected source can support…"><div class="actions"><button class="primary" id="ask">Ask source</button></div>`;$("#ask").onclick=async()=>{const q=$("#question").value.trim();if(!q)return;state.chat.push({role:"user",text:q});chatPane();try{const r=await api(`/api/documents/${d.id}/chat`,{method:"POST",body:{question:q}});state.chat.push({role:"ai",text:r.answer+((r.citations||[]).length?"\n\n"+r.citations.map(c=>`${c.marker} · Page ${c.page} · ${c.section}`).join("\n"):"")});chatPane()}catch(e){toast(e.message)}}}
function comparePane(){if(state.docs.length<2)return $("#rightPane").innerHTML=`<div class="empty"><b>Two sources required</b><small>Upload at least two documents to run a comparison.</small></div>`;const opts=state.docs.map(d=>`<option value="${d.id}">${esc(d.title)}</option>`).join("");$("#rightPane").innerHTML=`<label>Source A<select id="docA">${opts}</select></label><label>Source B<select id="docB">${opts}</select></label><div class="actions"><button class="primary" id="compare">Run comparison</button></div><div id="compareResult"></div>`;$("#compare").onclick=async()=>{try{const r=await api("/api/documents/compare",{method:"POST",body:{documentIds:[$("#docA").value,$("#docB").value]}});$("#compareResult").innerHTML=`<div class="compare-block"><b>ADDED</b><pre>${esc((r.addedClauses||[]).join("\n"))}</pre></div><div class="compare-block"><b>REMOVED</b><pre>${esc((r.removedClauses||[]).join("\n"))}</pre></div><div class="compare-block"><b>CHANGED DATES</b><pre>${esc(JSON.stringify(r.changedDates||{},null,2))}</pre></div>`}catch(e){toast(e.message)}}}
async function verify(id){try{const r=await api(`/api/transformations/${id}/verify`,{method:"POST",body:{}});toast(`Re-verified · factuality ${r.factualityScore}% · unsupported ${r.unsupported}`);await refresh()}catch(e){toast(e.message)}}
async function saveVersion(id){const el=document.querySelector(`[data-edit="${id}"]`);if(!el)return;try{await api(`/api/transformations/${id}/version`,{method:"POST",body:{content:el.innerText}});await refresh();toast("Version committed") }catch(e){toast(e.message)}}
async function copy(id){const o=state.outputs.find(x=>x.id===id);if(!o)return;try{await navigator.clipboard.writeText(o.content);toast("Artifact copied")}catch{toast("Clipboard access unavailable")}}
async function exportOut(id,format){try{const r=await api(`/api/exports/${id}`,{method:"POST",body:{format}});const blob=new Blob([r.content],{type:format==="json"?"application/json":"text/markdown"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=r.filename;a.click();URL.revokeObjectURL(a.href)}catch(e){toast(e.message)}}
async function api(path,opt={}){const r=await fetch(path,{method:opt.method||"GET",headers:{"Content-Type":"application/json",...(state.token?{Authorization:`Bearer ${state.token}`}:{})},body:opt.body?JSON.stringify(opt.body):undefined});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`Request failed (${r.status})`);return data}
function fileToBase64(file){return new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(String(fr.result).split(",")[1]||"");fr.onerror=reject;fr.readAsDataURL(file)})}
function logout(){localStorage.removeItem("morph_token");state.token=null;state.user=null;landing()}
function metric(label,value,kicker){return `<div class="metric-card"><span>${kicker}</span><small>${esc(label)}</small><b>${value??0}</b></div>`}
function chart(obj={}){const entries=Object.entries(obj||{}),max=Math.max(1,...entries.map(x=>Number(x[1])||0));return `<div class="chart">${entries.slice(0,8).map(([k,v])=>`<div class="bar"><span>${esc(k)}</span><i><em style="width:${(Number(v)||0)/max*100}%"></em></i><b>${v}</b></div>`).join("")||'<small class="muted">No data yet.</small>'}</div>`}
function select(id,values,selected=values[0],klass=""){return `<label class="${klass}">${title(id)}<select id="${id}">${values.map(x=>`<option ${x===selected?"selected":""}>${esc(x)}</option>`).join("")}</select></label>`}
function title(s){return s.replace(/([A-Z])/g," $1").replace(/^./,x=>x.toUpperCase())}
function modeName(){return modeLabel(state.mode)}
function modeLabel(m){return({standard:"STANDARD MORPH",oracle:"ORACLE MODE",clearance:"CLEARANCE MORPH",swarm:"SWARM INGESTION",decoy:"HONEY-POT DECOY",bias:"BIAS NEUTRALIZER"})[m]||"STANDARD MORPH"}
function featureIcon(k){return({immune:"◈",trace:"⌁",confidence:"◉",redact:"▣",swarm:"✣",oracle:"◇",decoy:"◆",bias:"≋",echo:"↺",fingerprint:"#"})[k]||"•"}
function navIcon(k){return({dashboard:"⌂",transform:"↗",documents:"▤",history:"◷",features:"✦",analytics:"▥",settings:"⚙"})[k]||"•"}
function esc(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function toast(text){const t=document.createElement("div");t.className="toast";t.textContent=text;$("#toast").append(t);setTimeout(()=>t.remove(),4500)}
