const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],app=$("#app");
const OUTPUTS=["Citizen Simplifier","Officer Brief","Executive Summary","FAQ Generator","WhatsApp Generator","Social Media Generator","Presentation Generator","Voice Script","Press Release","SMS / Alert","Infographic Content","Detailed Report","Key Facts / Statistics","Action Checklist"];
const LANGUAGES=["English","Hindi","Hinglish","Tamil","Telugu","Bengali","Marathi","Gujarati","Kannada","Malayalam","Punjabi","Odia"];
const NAV=[["dashboard","Command Center"],["transform","MORPH Studio"],["documents","Source Library"],["history","Output Vault"],["features","Capabilities"],["analytics","Analytics"],["audit","Audit & Provenance"],["settings","System"]];
const CAPABILITIES=[["Document Ingestion","PDF, DOCX, TXT, Markdown and pasted source text."],["Document Intelligence","Claims, entities, dates, numbers, topics and review signals."],["Immune System","Scan source text for prompt-injection-style instructions."],["MORPH Studio","Fourteen source-grounded output formats with audience, tone, channel and language controls."],["Glass Box Traceability","Inspect source evidence attached to an artifact."],["Confidence & Ambiguity","Expose verification scores instead of silently guessing."],["Clearance / Redaction","Create a deterministic sanitized working copy."],["Bias Neutralizer","Create an objective working copy while retaining attribution."],["Ask MORPH","Ask questions against retrieved source chunks."],["Conflict Comparison","Compare two sources for changed information."],["Review & Approval","Approve or request revision before export."],["Versioning & Export","Save versions and export Markdown or JSON with provenance."]];
const state={token:localStorage.getItem("morph_token"),user:null,view:"dashboard",docs:[],outputs:[],analytics:{},activeDoc:null,chat:[],audit:JSON.parse(localStorage.getItem("morph_audit")||"[]"),review:JSON.parse(localStorage.getItem("morph_review")||"{}"),decoy:""};
boot();
async function api(path,o={}){const r=await fetch(path,{method:o.method||"GET",headers:{"Content-Type":"application/json",...(state.token?{Authorization:`Bearer ${state.token}`}:{})},body:o.body===undefined?undefined:JSON.stringify(o.body)});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||`Request failed (${r.status})`);return d}
async function boot(){if(!state.token)return landing();try{state.user=(await api("/api/me")).user;await refresh();render()}catch{localStorage.removeItem("morph_token");state.token=null;landing()}}
async function refresh(){const[d,o,a]=await Promise.all([api("/api/documents"),api("/api/transformations"),api("/api/analytics")]);state.docs=d.documents||[];state.outputs=o.outputs||[];state.analytics=a||{};if(!state.activeDoc||!state.docs.some(x=>x.id===state.activeDoc.id))state.activeDoc=state.docs[0]||null}
function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
function persist(){localStorage.setItem("morph_audit",JSON.stringify(state.audit.slice(-200)));localStorage.setItem("morph_review",JSON.stringify(state.review))}
function logEvent(a,d=""){state.audit.push({action:a,detail:d,createdAt:new Date().toISOString()});persist()}
function toast(m){const e=$("#toast");if(!e)return;e.textContent=m;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2500)}
function landing(){app.innerHTML=`<div class="landing"><header class="topbar"><div class="brand"><span class="seal">M</span><div><b>MORPH</b><small>INTELLIGENCE TRANSFORMATION OS</small></div></div><div><button class="ghost" data-action="register">Create Account</button><button class="primary" data-action="login">Officer Login</button></div></header><main class="landing-main"><section class="hero-copy"><div class="eyebrow">SOURCE-GROUNDED INTELLIGENCE → VERIFIED COMMUNICATION</div><h1>MORPH</h1><h2>One trusted source.<br><em>Every mission-ready message.</em></h2><p>Transform policy documents, alerts and intelligence into audience-specific communication while preserving source evidence, verification status and human review.</p><div class="hero-actions"><button class="primary large" data-action="login">Enter Command Center →</button><button class="ghost large" data-action="register">Create Workspace</button></div><div class="trust-row"><span>● Source grounded</span><span>● Traceable</span><span>● Verified</span><span>● Human controlled</span></div></section><section class="landing-console"><div class="console-top"><span>MORPH / OPERATIONAL CORE</span><span class="online">● SYSTEM READY</span></div><h3>INGEST → UNDERSTAND → MORPH → VERIFY → REVIEW</h3><p>One evidence model powers the entire workspace.</p><div class="pipeline-preview">${["Ingest","Understand","Morph","Verify","Publish"].map((x,i)=>`<div><span>0${i+1}</span><b>${x}</b><small>${["PDF · DOCX · TXT · MD","Claims · entities · dates","Audience · tone · channel","Factuality · citations","Review · version · export"][i]}</small></div>`).join("")}</div><div class="cap-strip">${CAPABILITIES.slice(0,8).map(c=>`<span>${esc(c[0])}</span>`).join("")}</div></section></main></div>`;bindGlobal()}
function authPage(reg=false){app.innerHTML=`<main class="auth-page"><section class="panel auth-card"><div class="brand"><span class="seal">M</span><b>MORPH</b></div><div class="eyebrow">SECURE OPERATOR ACCESS</div><h1>${reg?"Create operator account":"Officer Login"}</h1><p class="muted">${reg?"Create a workspace account for source-grounded transformation.":"Authenticate to enter the MORPH command center."}</p><form id="authForm">${reg?'<label>Name<input name="name" maxlength="100" required></label>':""}<label>Email<input name="email" type="email" required></label><label>Password<input name="password" type="password" minlength="8" required></label><button class="primary full" type="submit">${reg?"Create Account":"Authenticate"} →</button><button class="ghost full" type="button" data-action="back">Back</button></form></section></main>`;bindGlobal()}
function render(){app.innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="brand sidebar-brand"><span class="seal">M</span><div><b>MORPH</b><small>INTELLIGENCE TRANSFORMATION OS</small></div></div><div class="secure-badge"><span class="pulse"></span> SECURE WORKSPACE</div><nav class="nav">${NAV.map(([k,l])=>`<button data-nav="${k}" class="${state.view===k?"active":""}"><span>◆</span>${l}</button>`).join("")}</nav><div class="sidebar-source"><span>ACTIVE SOURCE</span><b>${esc(state.activeDoc?.title||"None loaded")}</b><small>${state.activeDoc?`${esc((state.activeDoc.fileType||"DOC").toUpperCase())} · ${state.activeDoc.pages||1} page(s)`:"Open MORPH Studio to ingest"}</small></div><div class="user-box"><b>${esc(state.user?.name||"Operator")}</b><small>${esc(state.user?.role||"USER")} · ${esc(state.user?.email||"")}</small><button class="ghost full" data-action="logout">Sign out</button></div></aside><main class="main"><header class="main-top"><div><span class="crumb">MORPH / ${esc(pageTitle())}</span><h1>${esc(pageTitle())}</h1><p>${esc(pageSubtitle())}</p></div><div class="top-actions"><span class="session-badge">● VERIFIED SESSION</span><button class="primary" data-action="new">＋ New Transformation</button></div></header>${view()}</main></div>`;bindGlobal()}
function pageTitle(){return({dashboard:"Command Center",transform:"MORPH Studio",documents:"Source Library",history:"Output Vault",features:"Capabilities",analytics:"Operational Analytics",audit:"Audit & Provenance",settings:"System & Security"})[state.view]||"Command Center"}
function pageSubtitle(){return({dashboard:"Live operations from ingestion through verification and review.",transform:"Build, inspect and approve source-grounded communication artifacts.",documents:"Every analyzed source and its evidence profile.",history:"Versioned artifacts with factuality, citations and review state.",features:"Tier 1 capabilities plus safe deterministic tools available in this deployment.",analytics:"Usage, quality, language and source/output distribution.",audit:"Browser audit trail and artifact provenance fingerprints.",settings:"Runtime posture, authentication and safe deployment configuration."})[state.view]||""}
function view(){return({dashboard,transform:studio,documents,history:vault,features,analytics:analyticsView,audit:auditView,settings:settingsView}[state.view]||dashboard)()}
function metric(l,v,t){return `<div class="metric-card"><span>${esc(t)}</span><small>${esc(l)}</small><b>${esc(v)}</b></div>`}
function dashboard(){const a=state.analytics||{};return `<section class="metric-grid">${metric("Sources processed",a.documentsProcessed||0,"SOURCE")}${metric("Transformations",a.transformationsGenerated||0,"OPS")}${metric("Artifacts",a.outputsGenerated||0,"OUTPUT")}${metric("Languages",a.languagesUsed||0,"I18N")}${metric("Avg factuality",`${a.averageFactualityScore||0}%`,"VERIFY")}</section><section class="dashboard-grid"><div class="panel"><div class="section-head"><div><div class="eyebrow">CORE PIPELINE</div><h2>Source → intelligence → action</h2></div><button class="ghost" data-action="new">Open MORPH Studio</button></div><div class="flow">${[["01","INGEST","PDF · DOCX · TXT · MD"],["02","UNDERSTAND","CLAIMS · ENTITIES · DATES"],["03","MORPH","14 OUTPUT FORMATS"],["04","VERIFY","FACTUALITY · CITATIONS"],["05","REVIEW","APPROVE · EXPORT"]].map(x=>`<div class="flow-step"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></div>`).join("")}</div></div><div class="panel"><div class="section-head"><div><div class="eyebrow">GUARDRAILS</div><h2>Operational status</h2></div><span class="status-pill ok">READY</span></div>${[["Immune pre-flight","Scan source text before ingest"],["Traceability","Citation map per artifact"],["Verification","Unsupported content surfaced"],["Review","Approval state before export"],["Provenance","Fingerprint on exports"]].map(x=>`<div class="status-row"><span class="check">✓</span><div><b>${x[0]}</b><small>${x[1]}</small></div><span class="status-pill ok">ON</span></div>`).join("")}</div></section><section class="panel"><div class="section-head"><div><div class="eyebrow">RECENT SOURCES</div><h2>Source library</h2></div><button class="ghost" data-nav="documents">View all →</button></div>${docTable(state.docs.slice(0,6))}</section>`}
function studio(){const d=state.activeDoc;return `<section class="studio-grid"><section class="panel source-panel"><div class="section-head"><div><div class="eyebrow">01 / INGEST</div><h2>Trusted source</h2></div>${d?'<span class="status-pill ok">ANALYZED</span>':'<span class="status-pill">WAITING</span>'}</div><div class="drop" id="drop"><div class="drop-icon">↑</div><b>Drop a document here</b><small>PDF · DOCX · TXT · Markdown</small><span class="drop-hint">or click to browse</span></div><input id="fileInput" type="file" accept=".pdf,.docx,.txt,.md,.markdown"><textarea id="sourceText" placeholder="Paste trusted source material here…">${esc(d?.text||"")}</textarea><div class="row"><input id="department" placeholder="Department" value="${esc(d?.department||"General")}"><button class="primary" data-action="analyze">${d?"Re-analyze":"Analyze Source"} →</button></div>${d?sourceSummary(d):'<div class="helper">Nothing is transformed until a source has been analyzed.</div>'}<div class="special-tools"><div class="tool-title">SOURCE SAFETY & DERIVED VIEWS</div><button data-action="immune">Immune Scan</button><button data-action="redact">Clearance Redaction</button><button data-action="bias">Bias Neutralizer</button><button data-action="decoy">Synthetic Decoy</button></div>${state.decoy?`<div class="decoy-box"><span class="status-pill warn">SANDBOX / SYNTHETIC ONLY</span><h3>Honey-Pot Decoy Preview</h3><pre>${esc(state.decoy)}</pre><button class="ghost" data-action="copy-decoy">Copy decoy</button></div>`:""}</section><section class="panel controls-panel"><div class="section-head"><div><div class="eyebrow">02 / MORPH</div><h2>Transformation controls</h2></div><span class="mode-chip">SOURCE GROUNDED</span></div><div class="form-grid">${select("audience",["Citizen","Officer","Executive","Student","Media","General Public"],"Citizen")}${select("tone",["Formal","Simple","Professional","Friendly","Urgent","Educational"],"Professional")}${select("length",["Short","Medium","Detailed"],"Medium")}${select("channel",["Website","WhatsApp","Email","Social Media","SMS","Presentation","Report","Voice"],"Website")}${select("language",LANGUAGES,"English","full")}</div><div class="control-title">OUTPUT ARTIFACTS <button class="text-link" data-action="toggle-outputs">Toggle all</button></div><div class="output-picker">${OUTPUTS.map((x,i)=>`<label class="output-option"><input type="checkbox" name="outputType" value="${esc(x)}" ${i<5?"checked":""}><span>${esc(x)}</span></label>`).join("")}</div><button class="primary large full" data-action="generate" ${d?"":"disabled"}>Generate & Verify Artifacts →</button>${d?intelligence(d):'<div class="helper">Analyze a source to unlock generation.</div>'}</section><section class="panel result-panel"><div class="result-tabs"><button class="active" data-tab="outputs">Outputs</button><button data-tab="chat">Ask MORPH</button><button data-tab="compare">Conflicts</button></div><div id="rightPane">${generated()}</div></section></section>`}
function sourceSummary(d){const i=d.intelligence||{};return `<div class="source-summary"><div class="eyebrow">ACTIVE SOURCE</div><b>${esc(d.title)}</b><small>${esc((d.fileType||"TEXT").toUpperCase())} · ${i.wordCount||0} words · ${i.pages||d.pages||1} page(s)</small><div class="mini-stats"><span><b>${i.claimCount||0}</b> claims</span><span><b>${i.entityCount||0}</b> entities</span><span><b>${i.citationCount||0}</b> citations</span></div></div>`}
function intelligence(d){const i=d.intelligence||{};return `<div class="intel"><div class="control-title">SOURCE INTELLIGENCE</div><div class="intel-grid"><div><span>WORDS</span><b>${i.wordCount||0}</b></div><div><span>CLAIMS</span><b>${i.claimCount||0}</b></div><div><span>ENTITIES</span><b>${i.entityCount||0}</b></div><div><span>PAGES</span><b>${i.pages||d.pages||1}</b></div></div><div class="chips">${(i.topics||[]).map(x=>`<span class="chip">${esc(x)}</span>`).join("")}</div>${(i.risks||[]).length?`<div class="risk-box"><b>REVIEW SIGNALS</b>${i.risks.slice(0,4).map(x=>`<span>${esc(x)}</span>`).join("")}</div>`:""}</div>`}
function generated(){const os=state.outputs.filter(o=>!state.activeDoc||o.documentIds?.includes(state.activeDoc.id)).slice(0,8);return os.length?os.map(outputCard).join(""):empty("No artifacts generated","Analyze a source, select outputs and generate verified artifacts.")}
function outputCard(o){const review=state.review[o.id]||"PENDING REVIEW",score=Number(o.factualityScore||0),trace=o.citationMap||[];return `<article class="output-card"><div class="output-head"><div><span class="eyebrow">ARTIFACT / ${esc(o.outputType)}</span><h3>${esc(o.title||o.outputType)}</h3></div><span class="status-pill ${score>=90?"ok":"warn"}">${score}% FACTUALITY</span></div><div class="output-meta"><span>${esc(o.language||"English")}</span><span>${esc(o.audience||"")}</span><span>${esc(o.channel||"")}</span><span>CITATIONS ${o.citationCoverage||0}%</span><span>REVIEW ${esc(review)}</span></div><div class="content" contenteditable="true" spellcheck="true" data-edit="${esc(o.id)}">${esc(o.content||"")}</div><details class="trace"><summary>Glass Box · source trace (${trace.length})</summary>${trace.length?trace.map(c=>`<div class="trace-row"><b>${esc(c.marker||"[source]")}</b><span>Page ${esc(c.page)} · ${esc(c.section)}</span><small>${esc(c.source||"")}</small></div>`).join(""):'<div class="helper">No citation map returned.</div>'}</details><div class="actions"><button data-action="copy" data-id="${esc(o.id)}">Copy</button><button data-action="save" data-id="${esc(o.id)}">Save Version</button><button data-action="verify" data-id="${esc(o.id)}">Re-verify</button><button data-action="approve" data-id="${esc(o.id)}">Approve</button><button data-action="revise" data-id="${esc(o.id)}">Request Revision</button><button data-action="export" data-id="${esc(o.id)}" data-format="md">Export MD</button><button data-action="export" data-id="${esc(o.id)}" data-format="json">Export JSON</button></div></article>`}
function documents(){return `<section class="panel"><div class="section-head"><div><div class="eyebrow">SOURCE LIBRARY</div><h2>Analyzed documents</h2></div><button class="primary" data-action="new">＋ New source</button></div>${docTable(state.docs)}</section>`}
function docTable(ds){if(!ds.length)return empty("No sources yet","Open MORPH Studio and analyze your first document.");return `<div class="table-wrap"><table class="table"><thead><tr><th>Source</th><th>Type</th><th>Intelligence</th><th>Created</th><th></th></tr></thead><tbody>${ds.map(d=>`<tr><td><b>${esc(d.title)}</b><small>${esc(d.name||"")}</small></td><td>${esc((d.fileType||"TXT").toUpperCase())}</td><td>${d.intelligence?.claimCount||0} claims · ${d.intelligence?.entityCount||0} entities</td><td>${formatDate(d.createdAt)}</td><td><button class="link-btn" data-action="open-doc" data-id="${esc(d.id)}">Open</button></td></tr>`).join("")}</tbody></table></div>`}
function vault(){return `<section class="panel"><div class="section-head"><div><div class="eyebrow">OUTPUT VAULT</div><h2>Generated artifacts</h2></div><span class="status-pill ok">${state.outputs.length} TOTAL</span></div>${state.outputs.length?state.outputs.map(outputCard).join(""):empty("No artifacts yet","Run a transformation from a trusted source.")}</section>`}
function features(){return `<section class="capability-grid">${CAPABILITIES.map((c,i)=>`<article class="capability-card"><div class="cap-top"><span>${String(i+1).padStart(2,"0")}</span><span class="status-pill ok">TIER 1 · WORKING</span></div><div class="cap-icon">◆</div><h2>${esc(c[0])}</h2><p>${esc(c[1])}</p></article>`).join("")}<article class="capability-card sandbox"><div class="cap-top"><span>13</span><span class="status-pill warn">TIER 3 · SANDBOX</span></div><div class="cap-icon">◇</div><h2>Synthetic Decoy</h2><p>Deterministic fictionalization for demonstration only.</p></article></section>`}
function analyticsView(){const a=state.analytics||{};return `<section class="metric-grid">${metric("Sources",a.documentsProcessed||0,"SOURCE")}${metric("Artifacts",a.outputsGenerated||0,"OUTPUT")}${metric("Factuality",`${a.averageFactualityScore||0}%`,"VERIFY")}${metric("Citation coverage",`${a.averageCitationCoverage||0}%`,"TRACE")}${metric("Languages",a.languagesUsed||0,"I18N")}</section><section class="analytics-grid"><div class="panel"><div class="eyebrow">OUTPUT MIX</div><h2>Artifact types</h2><div class="chart">${bars(a.byType||{})}</div></div><div class="panel"><div class="eyebrow">LANGUAGES</div><h2>Language mix</h2><div class="chart">${bars(a.byLanguage||{})}</div></div><div class="panel"><div class="eyebrow">DEPARTMENTS</div><h2>Source distribution</h2><div class="chart">${bars(a.byDepartment||{})}</div></div></section>`}
function auditView(){const ev=state.audit.slice().reverse();return `<section class="panel"><div class="section-head"><div><div class="eyebrow">AUDIT / LOCAL SESSION TRAIL</div><h2>Operator activity</h2></div><button class="ghost" data-action="clear-audit">Clear local trail</button></div>${ev.length?`<div class="audit-list">${ev.map(e=>`<div class="audit-row"><span>${formatDate(e.createdAt)}</span><b>${esc(e.action)}</b><small>${esc(e.detail||"")}</small></div>`).join("")}</div>`:empty("No audit events","Actions from this browser will appear here.")}</section><section class="panel"><div class="eyebrow">PROVENANCE</div><h2>Artifact fingerprints</h2>${state.outputs.length?state.outputs.slice(0,12).map(o=>`<div class="provenance-row"><span>${esc(o.outputType)}</span><small>${esc(o.provider||"unknown")} · ${esc(o.model||"")} · ${formatDate(o.createdAt)}</small><b>${fingerprint(o)}</b></div>`).join(""):empty("No artifacts","Generate an artifact to see provenance.")}</section>`}
function settingsView(){return `<section class="settings-grid"><div class="panel"><div class="eyebrow">DEPLOYMENT</div><h2>Runtime posture</h2>${setting("Provider",state.analytics?.provider||"Server provider","No frontend provider secret")}${setting("Database",location.hostname.includes("localhost")?"Local JSON / PostgreSQL-ready":"PostgreSQL","Server-side storage")}${setting("Authentication","Signed bearer sessions","Protected API")}${setting("Parsing","PDF · DOCX · TXT · MD","Server-side extraction")}</div><div class="panel"><div class="eyebrow">CURRENT OPERATOR</div><h2>${esc(state.user?.name||"Operator")}</h2>${setting("Role",state.user?.role||"USER","")}${setting("Email",state.user?.email||"","Session identity")}<button class="ghost full" data-action="logout">Sign out</button></div></section>`}
function setting(k,v,n){return `<div class="setting-row"><span>${esc(k)}</span><b>${esc(v)}</b><i>${esc(n)}</i></div>`}
function bars(o){const e=Object.entries(o).sort((a,b)=>Number(b[1])-Number(a[1])).slice(0,8),m=Math.max(1,...e.map(x=>Number(x[1])||0));return e.length?e.map(([k,v])=>`<div class="bar"><span>${esc(k)}</span><i><em style="width:${Math.max(5,Math.round((Number(v)||0)/m*100))}%"></em></i><b>${esc(v)}</b></div>`).join(""):empty("No data yet","")}
function select(id,opts,selected=opts[0],extra=""){return `<label class="${extra}"><span>${esc(id[0].toUpperCase()+id.slice(1))}</span><select id="${id}">${opts.map(x=>`<option value="${esc(x)}" ${x===selected?"selected":""}>${esc(x)}</option>`).join("")}</select></label>`}
function empty(t,p){return `<div class="empty"><div class="empty-mark">◇</div><b>${esc(t)}</b><small>${esc(p)}</small></div>`}
function formatDate(v){if(!v)return "—";try{return new Date(v).toLocaleString()}catch{return String(v)}}
function fingerprint(o){return hash(`${o.id}|${o.version||1}|${o.createdAt||""}|${o.content||""}`)}
function hash(t){let h=2166136261;for(let i=0;i<t.length;i++){h^=t.charCodeAt(i);h=Math.imul(h,16777619)}return (`00000000${(h>>>0).toString(16)}`).slice(-8).toUpperCase()}
function safeName(v){return String(v).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"morph-artifact"}
function fileToBase64(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result).split(",")[1]||"");r.onerror=rej;r.readAsDataURL(file)})}
function bindGlobal(){app.onclick=handleClick;app.onsubmit=async e=>{if(e.target.id!=="authForm")return;e.preventDefault();try{const form=Object.fromEntries(new FormData(e.target)),reg=Boolean(form.name),r=await api(reg?"/api/auth/register":"/api/auth/login",{method:"POST",body:form});state.token=r.token;state.user=r.user;localStorage.setItem("morph_token",r.token);logEvent(reg?"register":"login",state.user.email);await refresh();render()}catch(err){toast(err.message)}};$$('[data-nav]').forEach(b=>b.onclick=()=>{state.view=b.dataset.nav;state.chat=[];state.decoy="";render()});$$('[data-tab]').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));if(state.view==="transform")wireStudio()}
async function handleClick(e){const b=e.target.closest("[data-action]");if(!b)return;const a=b.dataset.action;if(a==="login")return authPage(false);if(a==="register")return authPage(true);if(a==="back")return landing();if(a==="logout")return logout();if(a==="new"){state.activeDoc=null;state.chat=[];state.decoy="";state.view="transform";logEvent("new transformation");return render()}if(a==="analyze")return upload();if(a==="generate")return generate();if(a==="toggle-outputs"){const x=$$('[name="outputType"]'),all=x.every(v=>v.checked);x.forEach(v=>v.checked=!all);return}if(a==="open-doc"){state.activeDoc=state.docs.find(d=>d.id===b.dataset.id)||null;state.view="transform";return render()}if(a==="copy")return copyOutput(b.dataset.id);if(a==="save")return saveVersion(b.dataset.id);if(a==="verify")return reverify(b.dataset.id);if(a==="approve")return review(b.dataset.id,"APPROVED");if(a==="revise")return review(b.dataset.id,"REVISION REQUIRED");if(a==="export")return exportOutput(b.dataset.id,b.dataset.format);if(a==="immune")return immuneScan();if(a==="redact")return redactSource();if(a==="bias")return biasNeutralize();if(a==="decoy")return makeDecoy();if(a==="copy-decoy")return copyText(state.decoy||"");if(a==="clear-audit"){state.audit=[];persist();return render()}}
function wireStudio(){const d=$("#drop"),i=$("#fileInput");if(!d||!i)return;d.onclick=()=>i.click();d.ondragover=e=>{e.preventDefault();d.classList.add("active")};d.ondragleave=()=>d.classList.remove("active");d.ondrop=e=>{e.preventDefault();d.classList.remove("active");if(e.dataTransfer.files[0]){const dt=new DataTransfer();dt.items.add(e.dataTransfer.files[0]);i.files=dt.files;d.querySelector("b").textContent=i.files[0].name}};i.onchange=()=>{if(i.files[0])d.querySelector("b").textContent=i.files[0].name}}
function switchTab(t){$$('[data-tab]').forEach(x=>x.classList.toggle("active",x.dataset.tab===t));const p=$("#rightPane");if(!p)return;if(t==="outputs")p.innerHTML=generated();if(t==="chat"){p.innerHTML=chatPane();bindChat()}if(t==="compare"){p.innerHTML=comparePane();bindCompare()}}
function chatPane(){if(!state.activeDoc)return empty("No source selected","Analyze a document before using Ask MORPH.");return `<div class="chat"><div class="chat-log">${state.chat.length?state.chat.map(m=>`<div class="msg ${esc(m.role)}">${esc(m.text)}</div>`).join(""):empty("Ask about the selected source","Answers are grounded in retrieved source chunks.")}</div><div class="chat-input"><input id="question" placeholder="What is the deadline? What action is required?"><button class="primary" id="ask">Ask</button></div></div>`}
function bindChat(){$("#ask")?.addEventListener("click",ask);$("#question")?.addEventListener("keydown",e=>{if(e.key==="Enter")ask()})}
async function ask(){const q=$("#question")?.value.trim();if(!q||!state.activeDoc)return;state.chat.push({role:"user",text:q});switchTab("chat");try{const r=await api(`/api/documents/${state.activeDoc.id}/chat`,{method:"POST",body:{question:q}}),c=(r.citations||[]).map(x=>`${x.marker||"[source]"} · Page ${x.page} · ${x.section}`).join("\n");state.chat.push({role:"ai",text:(r.answer||"No verified answer returned.")+(c?`\n\n${c}`:"")});logEvent("document chat",q);switchTab("chat")}catch(err){toast(err.message)}}
function comparePane(){if(state.docs.length<2)return empty("Two sources required","Analyze at least two documents before comparing them.");return `<div class="compare"><div class="compare-selects">${selectObj("docA",state.docs,state.docs[0]?.id)}${selectObj("docB",state.docs,state.docs[1]?.id)}</div><button class="primary" id="compare">Compare sources →</button><div id="compareResult"></div></div>`}
function selectObj(id,docs,selected){return `<label><span>${id==="docA"?"Source A":"Source B"}</span><select id="${id}">${docs.map(d=>`<option value="${esc(d.id)}" ${d.id===selected?"selected":""}>${esc(d.title)}</option>`).join("")}</select></label>`}
function bindCompare(){$("#compare")?.addEventListener("click",async()=>{const a=$("#docA")?.value,b=$("#docB")?.value;if(!a||!b||a===b)return toast("Choose two different sources.");try{const r=await api("/api/documents/compare",{method:"POST",body:{documentIds:[a,b]}});$("#compareResult").innerHTML=`<div class="diff-grid"><div><h3>Added clauses</h3><pre>${esc((r.addedClauses||[]).join("\n")||"None")}</pre></div><div><h3>Removed clauses</h3><pre>${esc((r.removedClauses||[]).join("\n")||"None")}</pre></div><div><h3>Changed dates</h3><pre>${esc(JSON.stringify(r.changedDates||{},null,2))}</pre></div><div><h3>Changed numbers</h3><pre>${esc(JSON.stringify(r.changedNumbers||{},null,2))}</pre></div></div>`;logEvent("compare sources",`${a} vs ${b}`)}catch(err){toast(err.message)}})}
async function upload(){const i=$("#fileInput"),file=i?.files?.[0],text=$("#sourceText")?.value.trim();if(!file&&!text)return toast("Choose a file or paste source text.");let content=text,name="Pasted source.txt",type="text/plain";if(file){name=file.name;type=file.type||"application/octet-stream";content=await fileToBase64(file)}const hits=scan(content);if(hits.length){if(!confirm(`Immune System found ${hits.length} suspicious instruction pattern(s). Remove those lines and continue?`))return;content=stripInjectedLines(content)}const btn=$("[data-action=analyze]");if(btn){btn.disabled=true;btn.textContent="Analyzing…"}try{const r=await api("/api/documents/upload",{method:"POST",body:{name,type,encoding:file?"base64":"text",content,department:$("#department")?.value||"General"}});state.activeDoc=r.document;await refresh();state.activeDoc=state.docs.find(d=>d.id===r.document.id)||r.document;state.chat=[];logEvent("document analyzed",name);toast("Source analyzed successfully");render()}catch(err){toast(err.message)}finally{if(btn){btn.disabled=false;btn.textContent="Analyze Source →"}}}
async function generate(){if(!state.activeDoc)return toast("Analyze a source first.");const types=$$('[name="outputType"]:checked').map(x=>x.value);if(!types.length)return toast("Select at least one output.");const btn=$("[data-action=generate]");if(btn){btn.disabled=true;btn.textContent="Generating & verifying…"}try{await api("/api/transformations",{method:"POST",body:{documentIds:[state.activeDoc.id],outputTypes:types,audience:$("#audience").value,tone:$("#tone").value,length:$("#length").value,channel:$("#channel").value,language:$("#language").value}});await refresh();logEvent("artifacts generated",`${types.length} format(s)`);toast("Artifacts generated and verified");render()}catch(err){toast(err.message)}finally{if(btn){btn.disabled=false;btn.textContent="Generate & Verify Artifacts →"}}}
function scan(t){return String(t).match(/ignore\s+(all|previous|prior)\s+instructions|system\s+message|developer\s+message|reveal\s+(the\s+)?prompt|jailbreak|do\s+not\s+follow\s+the\s+source/gi)||[]}
function stripInjectedLines(t){return String(t).split("\n").filter(x=>!/(ignore\s+(all|previous|prior)\s+instructions|system\s+message|developer\s+message|reveal\s+(the\s+)?prompt|jailbreak)/i.test(x)).join("\n")}
function immuneScan(){const t=$("#sourceText")?.value||state.activeDoc?.text||"",h=scan(t);logEvent("immune scan",`${h.length} finding(s)`);toast(h.length?`Immune Scan: ${h.length} suspicious pattern(s) found.`:"Immune Scan: no suspicious instruction patterns detected.");if(h.length&&$("#sourceText"))$("#sourceText").value=stripInjectedLines(t)}
function redactSource(){const t=$("#sourceText")?.value||state.activeDoc?.text||"";if(!t.trim())return toast("Load a source first.");const r=t.replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi,"[REDACTED_EMAIL]").replace(/\b(?:\+?\d[\d\s().-]{8,}\d)\b/g,"[REDACTED_PHONE]").replace(/\b(?:aadhaar|passport|ssn|api key|token|secret|classified|confidential)\b[^\n]*/gi,"[REDACTED_SENSITIVE_LINE]");$("#sourceText").value=r+"\n\n[Clearance redaction working copy — review before analyzing]";logEvent("clearance redaction");toast("Sanitized working copy created.")}
function biasNeutralize(){const t=$("#sourceText")?.value||state.activeDoc?.text||"";if(!t.trim())return toast("Load a source first.");let r=t;for(const [a,b] of [["shocking","reported"],["outrageous","reported"],["obviously","the source states"],["clearly","the source states"],["extremely","notably"]])r=r.replace(new RegExp(`\\b${a}\\b`,"gi"),b);$("#sourceText").value=r+"\n\n[Bias-neutralized working copy — review attribution before publishing]";logEvent("bias neutralizer");toast("Objective working copy created.")}
function makeDecoy(){const t=$("#sourceText")?.value||state.activeDoc?.text||"";if(!t.trim())return toast("Load a source first.");state.decoy="SYNTHETIC DECOY — TRAINING / DEMONSTRATION ONLY\n\n"+t.replace(/\b20\d{2}\b/g,"2028").replace(/\b(?:INR|₹)\s?[\d,]+/gi,"INR 12,34,567").replace(/\b1077\b/g,"1188");logEvent("synthetic decoy generated");render()}
async function saveVersion(id){const e=document.querySelector(`[data-edit="${CSS.escape(id)}"]`);if(!e)return;try{await api(`/api/transformations/${id}/version`,{method:"POST",body:{content:e.innerText}});await refresh();logEvent("version saved",id);toast("Version saved");render()}catch(err){toast(err.message)}}
async function reverify(id){try{const r=await api(`/api/transformations/${id}/verify`,{method:"POST",body:{}});logEvent("artifact reverified",`${id} · ${r.factualityScore}%`);toast(`Re-verified: ${r.factualityScore}% factuality · ${r.citationCoverage}% citations`);await refresh();render()}catch(err){toast(err.message)}}
function review(id,s){state.review[id]=s;persist();logEvent("review status",`${id} → ${s}`);toast(s==="APPROVED"?"Artifact approved.":"Revision requested.");render()}
async function exportOutput(id,format){const o=state.outputs.find(x=>x.id===id);if(!o)return;if(state.review[id]!=="APPROVED"&&!confirm("This artifact is not approved. Export a review copy anyway?"))return;const p={fingerprint:fingerprint(o),exportedAt:new Date().toISOString(),operator:state.user?.email||"unknown",reviewStatus:state.review[id]||"PENDING REVIEW"};const payload=format==="json"?JSON.stringify({...o,provenance:p},null,2):`# ${o.title||o.outputType}\n\n${o.content||""}\n\n---\nFactuality: ${o.factualityScore||0}%\nCitation coverage: ${o.citationCoverage||0}%\nReview status: ${p.reviewStatus}\nFingerprint: ${p.fingerprint}`;const blob=new Blob([payload],{type:format==="json"?"application/json":"text/markdown"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=`${safeName(o.title||o.outputType)}.${format}`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u);logEvent("artifact exported",`${id} · ${format}`)}
function copyOutput(id){const o=state.outputs.find(x=>x.id===id);if(o)copyText(o.content||"")}
async function copyText(t){try{await navigator.clipboard.writeText(t);toast("Copied to clipboard")}catch{toast("Clipboard access unavailable")}}
function logout(){localStorage.removeItem("morph_token");state.token=null;state.user=null;state.docs=[];state.outputs=[];state.activeDoc=null;landing()}
